# Travis build, created 2014-1-16

sudo: required
dist: trusty

services:
  - docker

language: scala
scala:
    - "2.11.1"

before_install:
  - docker run --name mongod -d -p 27017:27017 mongo

# Running test coverage against scoverage:
# Disabled because of a bug in sbt-coveralls
# see: https://github.com/scoverage/sbt-coveralls/issues/28
#script: "sbt coverage test coveralls"

script: sbt coverage test coverageAggregate -Dsentinel.test.db_uri="mongodb://127.0.0.1:27017/sentinel-test"
