# Travis build, created 2014-1-16

language: scala
scala:
    - "2.11.1"

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update -qq
  - sudo apt-get install -y mongodb-org-server

# Looks like the service gets started upon install
#  - sudo service mongod start

# Running test coverage against scoverage:
script: "sbt coverage test coveralls"

